# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true
  deadline: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - testpackage
    - goerr113
    - wrapcheck
    - paralleltest
    - forbidigo
    - exhaustivestruct
    - ifshort
    - interfacer
    - maligned
    - forcetypeassert
    - cyclop # TODO review issues.

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
      path: "_test.go"
