name: gocan
on:
  pull_request:

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gocan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Annotate layout-only changes
        run: |
          curl -sLO https://github.com/vearutop/gocan/releases/download/v0.0.2/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz
          gocan_hash=$(git hash-object ./gocan)
          [ "$gocan_hash" == "0da18e8ea60c2addf699e3301aca6c103b2ae657" ] || (echo "::error::unexpected hash for gocan, possible tampering: $gocan_hash" && exit 1)
          git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.base.sha }}
          git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.head.sha }}
          ./gocan -gh-annotate -gh-base "${{ github.event.pull_request.base.sha }}" -gh-head ${{ github.event.pull_request.head.sha }}
